### ISSUE TITLE
HTTPError 

### ISSUE THREAD

**Issue by kkennethwu** [facebookresearch/robust_cvd#24]
Fine-tuning directory: '/content/family_run_output/R0-10_hierarchical2_midas2/StD100.0_StR1.0_SmD0_SmR0.0'
Loading weights:  models/midas_v21-f6b98070.pt
Downloading: "https://github.com/facebookresearch/WSL-Images/archive/master.zip" to /root/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    dp.process()
  File "/content/cvd2/process.py", line 234, in process
    return self.pipeline()
  File "/content/cvd2/process.py", line 170, in pipeline
    initial_depth_dir = self.compute_initial_depth()
  File "/content/cvd2/process.py", line 120, in compute_initial_depth
    self.out_dir, frames=None, base_dir=self.path, params=self.params
  File "/content/cvd2/depth_fine_tuning.py", line 223, in __init__
    self.model = model()
  File "/content/cvd2/monodepth/midas_v2_model.py", line 33, in __init__
    self.model = MidasNet(model_file, non_negative=True)
  File "/content/cvd2/monodepth/midas_v2/midas_net.py", line 28, in __init__
    self.pretrained, self.scratch = _make_encoder(features, use_pretrained_resnext)
  File "/content/cvd2/monodepth/midas_v2/blocks.py", line 13, in _make_encoder
    pretrained = _make_pretrained_resnext101_wsl(use_pretrained)
  File "/content/cvd2/monodepth/midas_v2/blocks.py", line 32, in _make_pretrained_resnext101_wsl
    resnet = torch.hub.load("facebookresearch/WSL-Images", "resnext101_32x8d_wsl")
  File "/usr/local/lib/python3.6/site-packages/torch/hub.py", line 337, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "/usr/local/lib/python3.6/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
  File "/usr/local/lib/python3.6/site-packages/torch/hub.py", line 394, in download_url_to_file
    u = urlopen(req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by remmel** [comment]
Duplicate https://github.com/facebookresearch/robust_cvd/issues/23

**Comment by remmel** [comment]
https://stackoverflow.com/a/69349309
in `blocks.py` replace
`resnet = torch.hub.load("facebookresearch/WSL-Images", "resnext101_32x8d_wsl")`
with
`resnet = torch.hub.load("facebookresearch/WSL-Images:main", "resnext101_32x8d_wsl")`
